# Generated by Django 4.2.4 on 2023-08-29 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
