# Generated by Django 4.2.4 on 2023-08-29 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0002_list_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='LM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField(max_length=255)),
                ('writer', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TMHL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField(max_length=255)),
                ('writer', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='WH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.CharField(max_length=255)),
                ('writer', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='list',
            name='file',
        ),
    ]
