# Generated by Django 4.2.4 on 2023-08-29 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0003_lm_tmhl_wh_remove_list_file'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TMHL',
        ),
    ]
